// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package br.ufs.dcomp.ChatRabbitMQ;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Mensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string emissor = 1;</code>
     */
    java.lang.String getEmissor();
    /**
     * <code>optional string emissor = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmissorBytes();

    /**
     * <code>optional string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>optional string hora = 3;</code>
     */
    java.lang.String getHora();
    /**
     * <code>optional string hora = 3;</code>
     */
    com.google.protobuf.ByteString
        getHoraBytes();

    /**
     * <code>optional string grupo = 4;</code>
     */
    java.lang.String getGrupo();
    /**
     * <code>optional string grupo = 4;</code>
     */
    com.google.protobuf.ByteString
        getGrupoBytes();

    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    boolean hasConteudo();
    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getConteudo();
    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder getConteudoOrBuilder();
  }
  /**
   * Protobuf type {@code Mensagem}
   */
  public  static final class Mensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Mensagem)
      MensagemOrBuilder {
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mensagem() {
      emissor_ = "";
      data_ = "";
      hora_ = "";
      grupo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              emissor_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              hora_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              grupo_ = s;
              break;
            }
            case 42: {
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder subBuilder = null;
              if (conteudo_ != null) {
                subBuilder = conteudo_.toBuilder();
              }
              conteudo_ = input.readMessage(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(conteudo_);
                conteudo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Mensagem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.Builder.class);
    }

    public static final int EMISSOR_FIELD_NUMBER = 1;
    private volatile java.lang.Object emissor_;
    /**
     * <code>optional string emissor = 1;</code>
     */
    public java.lang.String getEmissor() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emissor_ = s;
        return s;
      }
    }
    /**
     * <code>optional string emissor = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmissorBytes() {
      java.lang.Object ref = emissor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emissor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <code>optional string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>optional string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORA_FIELD_NUMBER = 3;
    private volatile java.lang.Object hora_;
    /**
     * <code>optional string hora = 3;</code>
     */
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hora = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRUPO_FIELD_NUMBER = 4;
    private volatile java.lang.Object grupo_;
    /**
     * <code>optional string grupo = 4;</code>
     */
    public java.lang.String getGrupo() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grupo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string grupo = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGrupoBytes() {
      java.lang.Object ref = grupo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grupo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEUDO_FIELD_NUMBER = 5;
    private br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo conteudo_;
    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    public boolean hasConteudo() {
      return conteudo_ != null;
    }
    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getConteudo() {
      return conteudo_ == null ? br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
    }
    /**
     * <code>optional .Conteudo conteudo = 5;</code>
     */
    public br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder getConteudoOrBuilder() {
      return getConteudo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEmissorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, emissor_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hora_);
      }
      if (!getGrupoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, grupo_);
      }
      if (conteudo_ != null) {
        output.writeMessage(5, getConteudo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEmissorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, emissor_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      if (!getHoraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hora_);
      }
      if (!getGrupoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, grupo_);
      }
      if (conteudo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getConteudo());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem other = (br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem) obj;

      boolean result = true;
      result = result && getEmissor()
          .equals(other.getEmissor());
      result = result && getData()
          .equals(other.getData());
      result = result && getHora()
          .equals(other.getHora());
      result = result && getGrupo()
          .equals(other.getGrupo());
      result = result && (hasConteudo() == other.hasConteudo());
      if (hasConteudo()) {
        result = result && getConteudo()
            .equals(other.getConteudo());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EMISSOR_FIELD_NUMBER;
      hash = (53 * hash) + getEmissor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HORA_FIELD_NUMBER;
      hash = (53 * hash) + getHora().hashCode();
      hash = (37 * hash) + GRUPO_FIELD_NUMBER;
      hash = (53 * hash) + getGrupo().hashCode();
      if (hasConteudo()) {
        hash = (37 * hash) + CONTEUDO_FIELD_NUMBER;
        hash = (53 * hash) + getConteudo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Mensagem)
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Mensagem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.class, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        emissor_ = "";

        data_ = "";

        hora_ = "";

        grupo_ = "";

        if (conteudoBuilder_ == null) {
          conteudo_ = null;
        } else {
          conteudo_ = null;
          conteudoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Mensagem_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem build() {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem result = new br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem(this);
        result.emissor_ = emissor_;
        result.data_ = data_;
        result.hora_ = hora_;
        result.grupo_ = grupo_;
        if (conteudoBuilder_ == null) {
          result.conteudo_ = conteudo_;
        } else {
          result.conteudo_ = conteudoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem.getDefaultInstance()) return this;
        if (!other.getEmissor().isEmpty()) {
          emissor_ = other.emissor_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHora().isEmpty()) {
          hora_ = other.hora_;
          onChanged();
        }
        if (!other.getGrupo().isEmpty()) {
          grupo_ = other.grupo_;
          onChanged();
        }
        if (other.hasConteudo()) {
          mergeConteudo(other.getConteudo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object emissor_ = "";
      /**
       * <code>optional string emissor = 1;</code>
       */
      public java.lang.String getEmissor() {
        java.lang.Object ref = emissor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emissor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string emissor = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmissorBytes() {
        java.lang.Object ref = emissor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emissor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string emissor = 1;</code>
       */
      public Builder setEmissor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emissor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string emissor = 1;</code>
       */
      public Builder clearEmissor() {
        
        emissor_ = getDefaultInstance().getEmissor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string emissor = 1;</code>
       */
      public Builder setEmissorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emissor_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hora_ = "";
      /**
       * <code>optional string hora = 3;</code>
       */
      public java.lang.String getHora() {
        java.lang.Object ref = hora_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hora_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hora = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHoraBytes() {
        java.lang.Object ref = hora_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hora_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hora = 3;</code>
       */
      public Builder setHora(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hora_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hora = 3;</code>
       */
      public Builder clearHora() {
        
        hora_ = getDefaultInstance().getHora();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hora = 3;</code>
       */
      public Builder setHoraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hora_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object grupo_ = "";
      /**
       * <code>optional string grupo = 4;</code>
       */
      public java.lang.String getGrupo() {
        java.lang.Object ref = grupo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          grupo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string grupo = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGrupoBytes() {
        java.lang.Object ref = grupo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          grupo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string grupo = 4;</code>
       */
      public Builder setGrupo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        grupo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string grupo = 4;</code>
       */
      public Builder clearGrupo() {
        
        grupo_ = getDefaultInstance().getGrupo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string grupo = 4;</code>
       */
      public Builder setGrupoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        grupo_ = value;
        onChanged();
        return this;
      }

      private br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo conteudo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder> conteudoBuilder_;
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public boolean hasConteudo() {
        return conteudoBuilder_ != null || conteudo_ != null;
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getConteudo() {
        if (conteudoBuilder_ == null) {
          return conteudo_ == null ? br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
        } else {
          return conteudoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          conteudo_ = value;
          onChanged();
        } else {
          conteudoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public Builder setConteudo(
          br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder builderForValue) {
        if (conteudoBuilder_ == null) {
          conteudo_ = builderForValue.build();
          onChanged();
        } else {
          conteudoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public Builder mergeConteudo(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo value) {
        if (conteudoBuilder_ == null) {
          if (conteudo_ != null) {
            conteudo_ =
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.newBuilder(conteudo_).mergeFrom(value).buildPartial();
          } else {
            conteudo_ = value;
          }
          onChanged();
        } else {
          conteudoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public Builder clearConteudo() {
        if (conteudoBuilder_ == null) {
          conteudo_ = null;
          onChanged();
        } else {
          conteudo_ = null;
          conteudoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder getConteudoBuilder() {
        
        onChanged();
        return getConteudoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder getConteudoOrBuilder() {
        if (conteudoBuilder_ != null) {
          return conteudoBuilder_.getMessageOrBuilder();
        } else {
          return conteudo_ == null ?
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.getDefaultInstance() : conteudo_;
        }
      }
      /**
       * <code>optional .Conteudo conteudo = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder> 
          getConteudoFieldBuilder() {
        if (conteudoBuilder_ == null) {
          conteudoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder, br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder>(
                  getConteudo(),
                  getParentForChildren(),
                  isClean());
          conteudo_ = null;
        }
        return conteudoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Mensagem)
    }

    // @@protoc_insertion_point(class_scope:Mensagem)
    private static final br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mensagem>
        PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Mensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Mensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConteudoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Conteudo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    java.lang.String getTipo();
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    com.google.protobuf.ByteString
        getTipoBytes();

    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>optional string corpo = 2;</code>
     */
    java.lang.String getCorpo();
    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>optional string corpo = 2;</code>
     */
    com.google.protobuf.ByteString
        getCorpoBytes();

    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    java.lang.String getNome();
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code Conteudo}
   */
  public  static final class Conteudo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Conteudo)
      ConteudoOrBuilder {
    // Use Conteudo.newBuilder() to construct.
    private Conteudo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Conteudo() {
      tipo_ = "";
      corpo_ = "";
      nome_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Conteudo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tipo_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              corpo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Conteudo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Conteudo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder.class);
    }

    public static final int TIPO_FIELD_NUMBER = 1;
    private volatile java.lang.Object tipo_;
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
     * </pre>
     *
     * <code>optional string tipo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORPO_FIELD_NUMBER = 2;
    private volatile java.lang.Object corpo_;
    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>optional string corpo = 2;</code>
     */
    public java.lang.String getCorpo() {
      java.lang.Object ref = corpo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        corpo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sequência de bytes que compõe o corpo da mensagem
     * </pre>
     *
     * <code>optional string corpo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCorpoBytes() {
      java.lang.Object ref = corpo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        corpo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nome_;
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
     * </pre>
     *
     * <code>optional string nome = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTipoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tipo_);
      }
      if (!getCorpoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, corpo_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nome_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTipoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tipo_);
      }
      if (!getCorpoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, corpo_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nome_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo)) {
        return super.equals(obj);
      }
      br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo other = (br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo) obj;

      boolean result = true;
      result = result && getTipo()
          .equals(other.getTipo());
      result = result && getCorpo()
          .equals(other.getCorpo());
      result = result && getNome()
          .equals(other.getNome());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIPO_FIELD_NUMBER;
      hash = (53 * hash) + getTipo().hashCode();
      hash = (37 * hash) + CORPO_FIELD_NUMBER;
      hash = (53 * hash) + getCorpo().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Conteudo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Conteudo)
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.ConteudoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Conteudo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Conteudo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.class, br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.Builder.class);
      }

      // Construct using br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tipo_ = "";

        corpo_ = "";

        nome_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.internal_static_Conteudo_descriptor;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getDefaultInstanceForType() {
        return br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.getDefaultInstance();
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo build() {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo buildPartial() {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo result = new br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo(this);
        result.tipo_ = tipo_;
        result.corpo_ = corpo_;
        result.nome_ = nome_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo) {
          return mergeFrom((br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo other) {
        if (other == br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo.getDefaultInstance()) return this;
        if (!other.getTipo().isEmpty()) {
          tipo_ = other.tipo_;
          onChanged();
        }
        if (!other.getCorpo().isEmpty()) {
          corpo_ = other.corpo_;
          onChanged();
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tipo_ = "";
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public java.lang.String getTipo() {
        java.lang.Object ref = tipo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tipo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTipoBytes() {
        java.lang.Object ref = tipo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder setTipo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tipo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder clearTipo() {
        
        tipo_ = getDefaultInstance().getTipo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       *
       * <code>optional string tipo = 1;</code>
       */
      public Builder setTipoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tipo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object corpo_ = "";
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>optional string corpo = 2;</code>
       */
      public java.lang.String getCorpo() {
        java.lang.Object ref = corpo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          corpo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>optional string corpo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCorpoBytes() {
        java.lang.Object ref = corpo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          corpo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>optional string corpo = 2;</code>
       */
      public Builder setCorpo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        corpo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>optional string corpo = 2;</code>
       */
      public Builder clearCorpo() {
        
        corpo_ = getDefaultInstance().getCorpo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       *
       * <code>optional string corpo = 2;</code>
       */
      public Builder setCorpoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        corpo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>optional string nome = 3;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>optional string nome = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>optional string nome = 3;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>optional string nome = 3;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       *
       * <code>optional string nome = 3;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Conteudo)
    }

    // @@protoc_insertion_point(class_scope:Conteudo)
    private static final br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo();
    }

    public static br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Conteudo>
        PARSER = new com.google.protobuf.AbstractParser<Conteudo>() {
      public Conteudo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Conteudo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Conteudo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Conteudo> getParserForType() {
      return PARSER;
    }

    public br.ufs.dcomp.ChatRabbitMQ.MessageProto.Conteudo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Mensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Mensagem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Conteudo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Conteudo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/message.proto\"c\n\010Mensag" +
      "em\022\017\n\007emissor\030\001 \001(\t\022\014\n\004data\030\002 \001(\t\022\014\n\004hor" +
      "a\030\003 \001(\t\022\r\n\005grupo\030\004 \001(\t\022\033\n\010conteudo\030\005 \001(\013" +
      "2\t.Conteudo\"5\n\010Conteudo\022\014\n\004tipo\030\001 \001(\t\022\r\n" +
      "\005corpo\030\002 \001(\t\022\014\n\004nome\030\003 \001(\tB)\n\031br.ufs.dco" +
      "mp.ChatRabbitMQB\014MessageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Mensagem_descriptor,
        new java.lang.String[] { "Emissor", "Data", "Hora", "Grupo", "Conteudo", });
    internal_static_Conteudo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Conteudo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Conteudo_descriptor,
        new java.lang.String[] { "Tipo", "Corpo", "Nome", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
